---

- name: mkdir ctmpls
  file: path=/etc/nginx/ctmpl state=directory

- name: copy ctmpls
  copy: src=nginx.conf.ctmpl dest=/etc/nginx/ctmpl/nginx.conf.ctmpl force=yes

- name: copy consul checker plugin
  copy: src=app_conf_service_instance_checker dest=/bin/app_conf_service_instance_checker mode=555

- name: copy consul nginx server config plugin
  copy: src=server_generator dest=/bin/server_generator mode=555

- name: config in file
  template: src=nginx.cfg.j2 dest=/opt/consul-template/config.d/nginx.cfg

- name: restart consul-template
  service: name=consul-template state=restarted

- name: ensure consul-template is running
  service: name=consul-template state=started
