---

- name: mkdir ctmpls
  file: path=/etc/nginx/ctmpl state=directory

- name: copy ctmpls
  copy: src={{item}} dest=/etc/nginx/ctmpl/{{item| regex_replace('^.*/ansible-nginx-consul-template\/files/(.*\.conf.ctmpl)$', '\\1')}} force=yes
  with_fileglob:
    - ./*

- name: config in file
  template: src=nginx.cfg.j2 dest=/opt/consul-template/config.d/nginx.cfg

- name: restart consul-template
  service: name=consul-template state=restarted

- name: ensure consul-template is running
  service: name=consul-template state=started
